version: "3.9"
services:
    address_api_php:
        container_name: address_api_application
        build: ../address-api/docker
        volumes:
            - ../address-api:/var/www/html
        depends_on:
            - address_api_nginx
            - kafka
        links:
            - address_api_nginx

    address_api_nginx:
        container_name: address_api_nginx
        image: nginx:1.21.6
        ports:
            - "8000:80"
        volumes:
            - ../address-api:/var/www/html
            - ../address-api/docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

    customer_api_php:
        container_name: customer_api_application
        build: ../customer-api/docker
        volumes:
            - ../customer-api:/var/www/html
            - ../customer-api/docker/config/supervisor/address-api-new-address.conf:/etc/supervisor/conf.d/address-api-new-address.conf
        environment:
            DB_HOST: customer_api_mysql
        depends_on:
            - customer_api_nginx
            - customer_api_mysql
            - kafka
        links:
            - customer_api_nginx
            - customer_api_mysql
        command: supervisord -n -c /etc/supervisor/supervisord.conf

    customer_api_nginx:
        container_name: customer_api_nginx
        image: nginx:1.21.6
        ports:
            - "8001:80"
        volumes:
            - ../customer-api:/var/www/html
            - ../customer-api/docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

    customer_api_mysql:
        image: mysql:8.0
        container_name: customer_api_mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        expose:
            - '3306'
        environment:
            MYSQL_DATABASE: 'customer_api'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ../customer-api/docker/init:/docker-entrypoint-initdb.d

    zookeeper:
        container_name: zookeeper
        image: 'bitnami/zookeeper:3.8.0'
        ports:
            - '2181:2181'
        volumes:
            - '../kafka/zookeeper-persistence:/bitnami/zookeeper'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        container_name: kafka
        image: 'bitnami/kafka:3.3.1'
        ports:
            - '9092:9092'
        volumes:
            - '../kafka/kafka-persistence:/bitnami/kafka'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper

    kafdrop:
        container_name: kafdrop
        image: obsidiandynamics/kafdrop:3.30.0
        ports:
            - '9000:9000'
        environment:
            - KAFKA_BROKERCONNECT=kafka:9092
        depends_on:
            - kafka
