version: "3.9"
services:
    environment:
        build: .
        container_name: address_api_application
        volumes:
            - ../:/var/www/html
        depends_on:
            - nginx
        links:
            - nginx
    nginx:
        image: nginx:1.21.6
        container_name: address_api_nginx
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html
            - ./config/nginx/application.conf:/etc/nginx/conf.d/default.conf
