version: "3.9"
services:
    zookeeper:
        container_name: zookeeper
        image: 'bitnami/zookeeper:3.8.0'
        ports:
            - '2181:2181'
        volumes:
            - './zookeeper-persistence:/bitnami/zookeeper'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        container_name: kafka
        image: 'bitnami/kafka:3.3.1'
        ports:
            - '9092:9092'
        volumes:
            - './kafka-persistence:/bitnami/kafka'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    kafdrop:
        container_name: kafdrop
        image: obsidiandynamics/kafdrop:3.30.0
        ports:
            - '9000:9000'
        environment:
            - KAFKA_BROKERCONNECT=kafka:9092
        depends_on:
            - kafka
