version: "3.9"
services:
    zookeeper:
        container_name: zookeeper
        image: 'bitnami/zookeeper:3.8.0'
        ports:
            - '2181:2181'
        volumes:
            - './zookeeper-persistence:/bitnami/zookeeper'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        container_name: kafka
        image: 'bitnami/kafka:3.3.1'
        ports:
            - '9092:9092'
        volumes:
            - './kafka-persistence:/bitnami/kafka'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
